# -*- coding: utf-8 -*-
"""S&D_TS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LnL_zpHD06qw13Vd346LSK6vZIcd0Jdk
"""

# Commented out IPython magic to ensure Python compatibility.
repo_name = "demo_applications"
project_name = "Stock_data"  # fill this in!

# Google Colab
try:
    from google.colab import drive
    drive.mount('/content/gdrive')
    import os
    os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/seclea/kaggle"
    # /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive
    # changing the working directory
    !mkdir /content/gdrive/MyDrive/seclea/
    !mkdir "/content/gdrive/MyDrive/seclea/{repo_name}"
    !mkdir "/content/gdrive/MyDrive/seclea/{repo_name}/{project_name}"
#     %cd "/content/gdrive/MyDrive/seclea/{repo_name}/{project_name}"
    print("Running on Colab, mounted drive and set kaggle path.")
except Exception:
    # not on Colab, do nothing.
    print("Running locally")
    pass

"""# 1.Downloading the data"""

!ls

!kaggle datasets download -d camnugent/sandp500

!unzip \*.zip  && rm *.zip

"""# 2.Data Exploration"""

# Commented out IPython magic to ensure Python compatibility.
# import the library
# %matplotlib inline
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# read full dataset
df = pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/all_stocks_5yr.csv')

"""# New Section"""

dateparse = lambda dates: pd.datetime.strptime(dates, '%Y-%m-%d')
GOOGL = pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/individual_stocks_5yr/individual_stocks_5yr/GOOGL_data.csv',sep=',', index_col='date', parse_dates=['date'], date_parser=dateparse).fillna(0)
EBAY= pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/individual_stocks_5yr/individual_stocks_5yr/EBAY_data.csv',sep=',', index_col='date', parse_dates=['date'], date_parser=dateparse).fillna(0)
AAPL= pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/individual_stocks_5yr/individual_stocks_5yr/AAPL_data.csv',sep=',', index_col='date', parse_dates=['date'], date_parser=dateparse).fillna(0)

GL=GOOGL.copy()
AP=AAPL.copy()
EB= EBAY.copy()

GOOGL.head()

"""#3 Checking for Stationarity"""

#Historical Closing price for all three GOOGLE, APPLE and EBAY
def plot(df, columns):
   for col in df.columns:
      if col in df.columns:
        df[columns].plot(xlabel='date',ylabel='label',legend=True,figsize=(10,4))
      return plt.ioff()

na= plot(GOOGL, ['open'])
na= plot(EBAY, ['open'])
na= plot(AAPL, ['open'])

V1= plot(GOOGL, ['close'])
V2=plot(EBAY, ['close'])
V3=plot(AAPL, ['close'])

"""-The first transaction of a business  for Google and Apple starts from 2013 to 2018 seems to be growing over time, however in the case of Ebay the opening price starts with a higher price, however in mid-2015 EBAY drops rapidly.

-The highest price reached in the day for Google and Apple starts in 2013 to 2018 seems to be growing, however in the case of Ebay the opening price starts with a higher price, however in mid-2015 EBAY drops rapidly.

-The highest price reached in the day for Google and Apple starts in 2013 to 2018 seems to be growing, however in the case of Ebay the opening price starts with a higher price, however in mid-2015 EBAY drops rapidly.

#4 Using of Dickey Fuller Test to confirm stationary
"""

from statsmodels.tsa.stattools import adfuller
#Test for staionarity
def test_stationarity(timeseries):
    #Determing rolling statistics
    rolmean = timeseries.rolling(12).mean()
    rolstd = timeseries.rolling(12).std()
    #Plot rolling statistics:
    plt.plot(timeseries, color='blue',label='Original')
    plt.plot(rolmean, color='red', label='Rolling Mean')
    plt.plot(rolstd, color='black', label = 'Rolling Std')
    plt.legend(loc='best')
    plt.title('Rolling Mean and Standard Deviation')
    plt.show(block=False)
    print("Results of dickey fuller test")
    adft = adfuller(timeseries,autolag='AIC')
    # output for dft will give us without defining what the values are.
    #hence we manually write what values does it explains using a for loop
    output = pd.Series(adft[0:4],index=['Test Statistics','p-value','No. of lags used','Number of observations used'])
    for key,values in adft[4].items():
        output['critical value (%s)'%key] =  values
    print(output)

test_stationarity(GOOGL.close)
test_stationarity(EBAY.close)
test_stationarity(AAPL.close)

"""In case of testing the critical value for opening stock market price,
test value for three stock market GOOGL, EBAY and APPL are (-0.5, ,-1.95,and 0.6) is greater than any critical value. In this case, we accept our null hypothesis and conclude that our data is not stationary,

# 5 Another way of testing stationary using KPSS
"""

# Import kpss
from statsmodels.tsa.stattools import kpss

result = kpss(GL.close)
print(result)
print('KPSS Test Statistic: %.2f' % result[0])
print('5%% Critical Value: %.2f' % result[3]['5%'])
print('p-value: %.2f' % result[1])

"""1. A very important point to note here is that the interpretation of KPSS is entirely opposite of the ADF test, and hence these tests cannot be used interchangeably.
  -Null Hypothesis, H0: The time series is stationary.
  -Alternative Hypothesis, H1: The time series is not stationary.

2. If the p-value is less than or equal to 0.05 or the absolute value of the test statistics is greater than the critical value, you reject H0 and conclude that  the time series is not stationary.

3. If the p-value is greater than 0.05 or the absolute value of the test statistics is less than the critical value, you fail to reject H0 and conclude that the time series is stationary.

4. In  case of the GOOGL closing price shows that the KPSS test value is higher than any other critical value so we raject the H0 the data is not stationary.

#5 Decompose the time series data with EBay stock
"""

from statsmodels.tsa.seasonal import seasonal_decompose

# Drop Null values
#EBAY.dropna(inplace=True)
#GOOGL.dropna(inplace=True)
#GOOGL.dropna(inplace=True)

"""# 6 Differencing to make the data stationary"""

#making the open price stationary
def conv_stat(df, columns):
  for col in df.columns:
      if col in df.columns:
        df['First Difference for open'] = df['open']- df['open'].shift(1)
        df['second Difference for open'] = df['open']- df['open'].shift(2)
        df['seasonal Difference for open'] = df['open']- df['open'].shift(12)

        return df

GOOGL = conv_stat(GOOGL, open)
EBAY = conv_stat(EBAY, open)
AAPL= conv_stat(AAPL, open)

new_GOOGL= (GOOGL['seasonal Difference for open'].dropna())
nw_AAPL=(AAPL['seasonal Difference for open'].dropna())
new_EBAY=(EBAY['seasonal Difference for open'].dropna())

"""We can see the test value close value is less for all the critical value  so we  reject the null hypthesis for all three stock market. So the data are stationay."""

#Plot open data for GOOGL
GOOGL['seasonal Difference for open'].plot()

#Plot open data for EBAY
EBAY['seasonal Difference for open'].plot()

#Plot open data for EBAY
AAPL['seasonal Difference for open'].plot()

#making the open price stationary
def conv_stat_close(df, columns):
  for col in df.columns:
      if col in df.columns:
        df['First Difference for close'] = df['close']- df['close'].shift(1)
        df['second Difference for close'] = df['close']- df['close'].shift(2)
        df['seasonal Difference for close'] = df['close']- df['close'].shift(12)
        return df

GOOGL = conv_stat_close(GOOGL, ['close'])
EBAY = conv_stat_close(EBAY, ['close'])
AAPL= conv_stat_close(AAPL, ['close'])

(GOOGL['seasonal Difference for close'].dropna())
(AAPL['seasonal Difference for close'].dropna())
(EBAY['seasonal Difference for close'].dropna())

GOOGL.head()

"""We can see the P-value for close less than 0.05 so we reject the null hypthesis for all three stock market. So the data are stationay."""

# Import kpss
from statsmodels.tsa.stattools import kpss

result = kpss(GL.close)
print(result)
print('KPSS Test Statistic: %.2f' % result[0])
print('5%% Critical Value: %.2f' % result[3]['5%'])
print('p-value: %.2f' % result[1])

#Plot open data for Google
GOOGL['seasonal Difference for close'].plot()

#Plot open data for Google
EBAY['seasonal Difference for close'].plot()

#Plot open data for Google
AAPL['seasonal Difference for close'].plot()

"""# 7 Plot differences for result before and after"""

plt.figure(figsize=(16, 6))
plt.plot(GOOGL.close, '-o', color='teal', label="original")
plt.plot(GOOGL['First Difference for close' ].diff(40), '-o', color='orange', label="differenced ts (lag=40)")
plt.legend(fontsize=12)

df_2 = GOOGL.close
GOOGL_diff = GOOGL['First Difference for close'].dropna()

plt.figure(figsize=(16,3))
plt.plot(GOOGL_diff, "-o", color='orange')

"""All the close and open data for three stock has been changed from non-stationary to stationary
-

# 8 Auto ARIMA Model
"""

GOOGL_Sea= (GOOGL['First Difference for close'].dropna())

GOOGL_Sea.tail()

train_data = GOOGL_Sea.loc['2013-02-11':'2016-12-01']
test_data = GOOGL_Sea.loc['2017-01-01':]

"""# 8.1 AutoRegression(AR)"""

from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
import matplotlib.pyplot as plt

# PACF plot of 1st differenced series
# PACF plot of 1st differenced series

def plot_ar(df):
  plt.rcParams.update({'figure.figsize':(9,3), 'figure.dpi':120})
  fig, axes = plt.subplots(1, 2, sharex=True)
  axes[0].plot(df.close.diff()); axes[0].set_title('1st Differencing')
  axes[1].set(ylim=(0,5))
  plot_pacf(df.close.diff().dropna(), ax=axes[1])
  return plt.show()

AAPL.head()
GOOGL.head()
EBAY.head()

"""#8.2 Moving Avrage (MA)"""

def plot_ma(df):
  plt.rcParams.update({'figure.figsize':(9,3), 'figure.dpi':120})
  fig, axes = plt.subplots(1, 2, sharex=True)
  axes[0].plot(df.close.diff()); axes[0].set_title('1st Differencing')
  axes[1].set(ylim=(0,1.2))
  plot_pacf(df.close.diff().dropna(), ax=axes[1])
  return plt.show()

AAPL.head()
GOOGL.head()
EBAY.head()

"""# 9 Build ARIMA Model for GOOGL

---


"""

!pip install numpy
!pip install pmdarima

# Commented out IPython magic to ensure Python compatibility.
import os
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.arima_process import ArmaProcess
from statsmodels.stats.diagnostic import acorr_ljungbox
#from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import pacf
from statsmodels.tsa.stattools import acf
from statsmodels.tsa.arima_model import ARIMA
#from pmdarima.arima import auto_arima
from tqdm import tqdm_notebook
# %matplotlib inline
from sklearn.metrics import mean_squared_error, mean_absolute_error
import math

GOOGL_Sea.head()

#from pmdarima.arima import auto_arima

#model_autoARIMA = auto_arima(train_data, start_p=0, start_q=0,
                      #test='adf',       # use adftest to find optimal 'd'
                      #max_p=3, max_q=3, # maximum p and q
                      #m=1,              # frequency of series
                      #d=None,           # let model determine 'd'
                      #seasonal=False,   # No Seasonality
                      #start_P=0,
                      #D=0,
                      #trace=True,
                      #error_action='ignore',
                      #suppress_warnings=True,
                      #stepwise=True)
#print(model_autoARIMA.summary())
#model_autoARIMA.plot_diagnostics(figsize=(15,8))
#plt.show()

train_data.head()
test_data.head()
GOOGL_Sea.head()
GOOGL.head()

"""the data in not seasonal the

# 12 Parameter Selection in time series

The optimal lag to use to make a relatively stationary version of our original time series

Parameter Selection for the ARIMA Time Series Model which are (p, d, q). These three parameters account for seasonality, trend, and noise in data:Making autocorrelation and partial autocorrelation charts help us choose hyperparameters for the ARIMA model.

The ACF gives us a measure of how much each "y" value is correlated to the previous n "y" values prior.

The PACF is the partial correlation function gives us (a sample of) the amount of correlation between two "y" values separated by n lags excluding the impact of all the "y" values in between them.

To determine p, q, d:

- AR model might be investigated first with lag length selected from the PACF or  via empirical investigation. In our case, it's clearly that within 0 lags the AR is significant. Which means, we can use AR = 0
- MA order (in the case where the MA is first tried then the MA order is being set to 1

so the ACF and PACF gives us p as 1 and q as 1 so we will build ARIMa model on the basis of this
"""

import itertools
# Define the d and q parameters to take any value between 0 and 1
q = d = range(0, 2)
# Define the p parameters to take any value between 0 and 3
p = range(0, 4)

# Generate all different combinations of p, q and q triplets
pdq = list(itertools.product(p, d, q))

# Generate all different combinations of seasonal p, q and q triplets
seasonal_pdq = [(x[0], x[1], x[2], 12) for x in list(itertools.product(p, d, q))]

print('parameter combinations for Seasonal ARIMA...')
print('SARIMAX: {} x {}'.format(pdq[1], seasonal_pdq[1]))
print('SARIMAX: {} x {}'.format(pdq[1], seasonal_pdq[2]))
print('SARIMAX: {} x {}'.format(pdq[2], seasonal_pdq[3]))
print('SARIMAX: {} x {}'.format(pdq[2], seasonal_pdq[4]))

#l_param = []
#l_param_seasonal=[]
#l_results_aic=[]
#for param in pdq:
   # for param_seasonal in seasonal_pdq:
       # try:
           # mod = sm.tsa.statespace.SARIMAX(train_data,
                                            #order=param,
                                           # seasonal_order=param_seasonal,
                                            #enforce_stationarity=False,
                                            #enforce_invertibility=False)

            #results = mod.fit()

            #print('ARIMA{}x{}12 - AIC:{}'.format(param, param_seasonal, results.aic))

           # l_param.append(param)
            #l_param_seasonal.append(param_seasonal)
           # l_results_aic.append(results.aic)
       # except:
          #  continue

# Plug the optimal parameter values into a new SARIMAX model
#ARIMA_MODEL = sm.tsa.statespace.SARIMAX(train_data,
#                                        order=(3, 1, 1),
                                        #seasonal_order=(3, 1, 1, 12),
                                        #enforce_stationarity=False,
                                        #enforce_invertibility=False)

# Fit the model and print results
#output = ARIMA_MODEL.fit()

#print(output.summary().tables[1])

# Call plot_diagnostics() on the results calculated above
#output.plot_diagnostics(figsize=(15, 18))
#plt.show()

"""
Let's check for these assumptions from diagnostics plots.

In the top right plot, we see that the red KDE line follows closely with the N(0,1) line (where N(0,1)) is the standard notation for a normal distribution with mean 0 and standard deviation of 1). This is a good indication that the residuals are normally distributed.

The normal qq-plot on the bottom left shows that the ordered distribution of residuals (blue dots) follows the linear trend of the samples taken from a standard normal distribution with N(0, 1). Again, this is a strong indication that the residuals are normally distributed.

The residuals over time (top left plot) don't display any obvious seasonality and appear to be white noise.  The time series residuals have low correlation with lagged versions of itself.

To conclude that  model has no correlations and provides a satisfactory fit to help forecast future values."""

#preds = output.fittedvalues

#GOOGL_Sea['predictions'] = GOOGL[GOOGL.columns[1]] * (1 + preds)
#GOOGL_Sea['predictions'].head()

##import plotly.graph_objects as go
#WINDOW_LENGTH = 100

#fig = go.Figure()
#fig.add_trace(go.Line(x=GOOGL_Sea.index[-WINDOW_LENGTH:], y=GOOGL_Sea[-WINDOW_LENGTH:], name='Actual',
                         #line=dict(color='blue', width=1)))
#fig.add_trace(go.Line(x=GOOGL_Sea.index[-WINDOW_LENGTH:], y=preds[-WINDOW_LENGTH:], name = 'Predictions',
                         #line=dict(color='red', width=1)
#))

#fig.update_layout(title='Predictions vs Actual Returns',
                  # xaxis_title='Year')
#fig.show()

"""#13 Test for Reseduial"""

#residuals = abs(GOOGL_Sea['predictions']- GOOGL['close'])

#plt.hist(residuals.values, bins=100)
#plt.show();

#residuals.plot(kind='kde')

#residuals.describe()

#plot_pacf(residuals)

"""The mean of the residual is close to Zero and there is no significant correlation also that we can see in the pacf plot for residuals

#14 Evaluation
"""

#y_test=test_data
#y_pred = GOOGL_Sea['predictions']
#print(y_test.shape, y_pred.shape)

# # Mean Absolute Error (MAE)
#MAE = np.mean(abs(y_pred - y_test))
#print('Mean Absolute Error (MAE): ' + str(np.round(MAE, 2)))

# Mean Squared Error (MSE)
#MSE = np.square(np.subtract(y_pred, y_test)).mean()
#print('Mean Squared Error (MSE): ' + str(np.round(MSE, 2)))
# Root Mean Squarred Error (RMSE)
#RMSE = np.sqrt(np.mean(np.square(y_pred - y_test)))
#print('Root Mean Squared Error (RMSE): ' + str(np.round(RMSE, 2)))
# Mean Absolute Percentage Error (MAPE)
#MAPE = np.mean((np.abs(np.subtract(y_test, y_pred)/ y_test))) * 100
#print('Mean Absolute Percentage Error (MAPE): ' + str(np.round(MAPE, 2)) + ' %')

GL.head()

GL1 = GL.copy()

GL1.close.head()

"""# Modeling For LSTM"""

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM

# Convert data to  stationary
def test_stationarity(timeseries):
    '''
    Input: timeseries (dataframe): timeseries for which we want to study the stationarity
    '''

    #Determing rolling statistics
    rolmean = timeseries.rolling(20).mean()
    rolstd = timeseries.rolling(20).std()

    #Plot rolling statistics:
    orig = plt.plot(timeseries, color='blue',label='Original')
    mean = plt.plot(rolmean, color='red', label='Rolling Mean')
    std = plt.plot(rolstd, color='black', label = 'Rolling Std')
    plt.legend(loc='best')
    plt.title('Rolling Mean & Standard Deviation')
    plt.show(block=False)

    #Perform Dickey-Fuller test:
    print('Results of Dickey-Fuller Test:')
    dftest = adfuller(timeseries, autolag='AIC')
    dfoutput = pd.Series(dftest[0:4], index=['Test Statistic','p-value',\
                                             '#Lags Used','Number of Observations Used'])
    for key,value in dftest[4].items():
        dfoutput['Critical Value (%s)'%key] = value
    print(dfoutput)

plt.figure(figsize = (10,6))
test_stationarity(GL.close.head(2000))

GL.close_log = GL.close.apply(np.log)
GL.close_tf = GL.close_log.apply(np.sqrt)

plt.figure(figsize = (10,6))
plt.plot(GL.close_tf)
plt.title('Transformed data')

print(GL.close_tf)

GL.close = GL.close_tf - GL.close_tf.shift()
GL_close_shift=GL.close.dropna()
plt.figure(figsize = (10,6))
test_stationarity(GL_close_shift)

"""# 15 Univariate LSTM Models"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM

"""-It is special kind of Recurrent Neural Network (RNN)used for long term dependencies

# 15.1 Vanilla model
"""

def preprocess_lstm(sequence, n_steps,n_features):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix >= len(sequence):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)

    X = np.array(X)
    y = np.array(y)

    X = X.reshape((X.shape[0], X.shape[1], n_features))
    return X, y

# choose the number of days on which to base our predictions
nb_days = 60

n_features = 1

X, y = preprocess_lstm(GL_close_shift.to_numpy(), nb_days, n_features)

#Split the data set between the training set and the test set
test_days = 365

X_train, y_train = X[:-test_days], y[:-test_days]
X_test, y_test = X[-test_days:], y[-test_days:]

train_original = GL1.close[:-test_days]
test_original = GL1.close[-test_days:]

plt.figure(figsize=(10,6))
plt.grid(True)
plt.xlabel('Dates')
plt.ylabel('Closing Prices')
plt.plot(train_original, 'b', label='Train data')
plt.plot(test_original, 'g', label='Test data')
plt.legend()

def vanilla_LSTM():
    model = Sequential()
    model.add(LSTM(units=50, input_shape=(nb_days, n_features)))
    model.add(Dense(1))
    return model

model = vanilla_LSTM()
model.summary()
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=[tf.keras.metrics.MeanAbsoluteError()])

model.fit(X_train,
          y_train,
          epochs=15,
          batch_size = 32)

# Evaluate the model on the test data using
print("Evaluate on test data")
results = model.evaluate(X_test, y_test, batch_size=32)
print("Test MSE:", results[0])
print("Test MAE:", results[1])

"""MSE and MAE both are less so it seems that model generalize well."""

# Prediction
y_pred = model.predict(X_test)

# We create a dataframe from y_pred to have date-time indexes.
pred_data = pd.DataFrame(y_pred[:,0], test_original.index,columns=['close'])

# Apply inverse transformation from 1.d

# Add the differenciation term
pred_data['close'] = pred_data['close'] + GL.close_tf.shift().values[-test_days:]

# Take the square, and the exponent
pred_data = pred_data.apply(np.square)
pred_data = pred_data.apply(np.exp)
# Plot actual prices vs predicted prices
plt.figure(figsize=(10,6))
plt.grid(True)
plt.xlabel('Dates')
plt.ylabel('Closing Prices')
plt.plot(test_original,'b',label='Actual prices')
plt.plot(pred_data, 'orange',label='Predicted prices')
plt.title('date'+ 'close')

plt.legend()

plt.figure(figsize=(10,6))
plt.grid(True)
plt.xlabel('Dates')
plt.ylabel('Closing Prices')
plt.plot(train_original, 'b', label='Train data')
plt.plot(test_original, 'g', label='Test data')
plt.plot(pred_data, 'orange', label='Prediction')
plt.title('date' + 'close')
plt.legend()

"""# 15.2 Stacked LSTM"""

GL1.head()

GL_ts= GL1.copy()

df1=GL_ts.reset_index()['close']

df1.head()

import matplotlib.pyplot as plt
plt.plot(df1)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
df1=scaler.fit_transform(np.array(df1).reshape(-1,1))

df1

df2= df1.copy()

##splitting dataset into train and test split
training_size=int(len(df1)*0.65)
test_size=len(df1)-training_size
train_data,test_data=df1[0:training_size,:],df1[training_size:len(df1),:1]

training_size,test_size

import numpy
# convert an array of values into a dataset matrix
def create_dataset(dataset, time_step=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-time_step-1):
		a = dataset[i:(i+time_step), 0]   ###i=0, X=0,1,2,3-----99   Y=100
		dataX.append(a)
		dataY.append(dataset[i + time_step, 0])
	return numpy.array(dataX), numpy.array(dataY)

# reshape into X=t,t+1,t+2..t+99 and Y=t+100
time_step = 100
X_train, y_train = create_dataset(train_data, time_step)
X_test, ytest = create_dataset(test_data, time_step)

print(X_train.shape), print(y_train.shape)

print(X_test.shape), print(ytest.shape)

# reshape input to be [samples, time steps, features] which is required for LSTM
X_train =X_train.reshape(X_train.shape[0],X_train.shape[1] , 1)
X_test = X_test.reshape(X_test.shape[0],X_test.shape[1] , 1)

# Create the Stacked LSTM model
model=Sequential()
model.add(LSTM(50,return_sequences=True,input_shape=(100,1)))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='adam')
model.summary()

model.fit(X_train,y_train,validation_data=(X_test,ytest),epochs=100,batch_size=64,verbose=1)

### check the prediction and check performance metrics
train_predict=model.predict(X_train)
test_predict=model.predict(X_test)

##Transformback to original form
train_predict=scaler.inverse_transform(train_predict)
test_predict=scaler.inverse_transform(test_predict)

### Calculate RMSE performance metrics
import math
from sklearn.metrics import mean_squared_error
math.sqrt(mean_squared_error(y_train,train_predict))

### Test Data RMSE
math.sqrt(mean_squared_error(ytest,test_predict))

"""# 15.3 Bidirectional Lstm"""

import numpy as np
import pandas_datareader as web
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout, SpatialDropout1D
from tensorflow import keras
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
plt.style.use('fivethirtyeight')

GL_ts.head()

#data
data = GL_ts.filter(['close'])
dataset = data.values
data_CNN= dataset.copy()
data_len = len(dataset)

data_CNN= dataset.copy()

#Apply MinMaxScaler / Normalisasi
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(dataset)

h = 360 #Jumlah test
inp = 30 #Besar input

data.iloc[0:data_len-h-inp,:]

data.iloc[data_len-(inp+h):data_len,:]

train_data = scaled_data[0:data_len-h-inp,:]
x_train = []
y_train = []
for i in range(inp, len(train_data)):
  x_train.append(train_data[i-inp:i, 0])
  y_train.append(train_data[i, 0])

x_train, y_train = np.array(x_train), np.array(y_train)
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

learning_rate = 0.003
epoch=10

model = Sequential()
model.add(LSTM(60, return_sequences=True, input_shape=(x_train.shape[1], 1)))
model.add(LSTM(100, return_sequences=False))
model.add(Dropout(0.4))
model.add(Dense(25))
model.add(Dense(1))

model.compile(optimizer = keras.optimizers.Adam(learning_rate=learning_rate), loss = 'mean_squared_error')
model.fit(x_train, y_train, batch_size=1, epochs=epoch)

test_data = scaled_data[data_len-(inp+h):data_len,:]
x_test = []
y_test = []
for i in range(inp, len(test_data)):
  x_test.append(test_data[i-inp:i, 0])
  y_test.append(test_data[i, 0])

x_test,y_test = np.array(x_test), np.array(y_test)

x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

predictions = model.predict(x_test)
print('r2_score: ',r2_score(y_test, predictions))
print('MAE: ', mean_absolute_error(y_test, predictions))
print('MSE: ', mean_squared_error(y_test, predictions,squared=True))
print('rmse: ',mean_squared_error(y_test, predictions,squared=False))
predictions = scaler.inverse_transform(predictions)

predictions[-1]

train = data[:data_len-h]
test = data[data_len-h:data_len]
test['Predictions'] = predictions
plt.figure(figsize=(20,10))
plt.xlabel('dates', fontsize = 16 )
plt.ylabel('close', fontsize = 16 )
plt.plot(train['close'],linewidth=1)
plt.plot(test[['close','Predictions']],linewidth=1)
plt.legend(['Train','Val','Predictions'], loc = 'lower right')
plt.show()

plt.figure(figsize=(10,10))
plt.plot(test[['close','Predictions']],linewidth=1.5)

"""# 15.4 CNN LSTM"""

# Commented out IPython magic to ensure Python compatibility.
from sklearn.preprocessing import MinMaxScaler

import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import math
import datetime

# %load_ext tensorboard
print(tf.version.VERSION)

# split dataset 80% train, 15% validation, 5% dev
def split_dataset(dataset):
    size = dataset.shape[0]
    train_size = size * 80 // 100
    test_size = size * 15 // 100

    return dataset[0:train_size, :], dataset[train_size:(train_size + test_size), :], dataset[(train_size + test_size):size, :]

def plot_series(time, series, lab, form='-', start=0, end=None):
    plt.plot(time[start:end], series[start:end], form, label=lab)
    plt.xlabel("Minute")
    plt.ylabel("Price")
    plt.grid(True)

def tf_dataset(series_x, series_y, batch_size, shuffle_buffer, shuffle=True):
    ds = tf.data.Dataset.from_tensor_slices((series_x, series_y))
    if shuffle:
        ds = ds.cache().shuffle(shuffle_buffer).batch(batch_size).repeat()
    else:
        ds = ds.cache().batch(batch_size).repeat()

    return ds

def create_window_dataset(ds, lb, window_size):
    windowed_dataset = []
    labels = []
    for i in range(window_size, ds.shape[0] + 1):
        windowed_dataset.append(ds[i - window_size:i])
        labels.append(lb[i - 1])

    return np.array(windowed_dataset), np.array(labels)

def get_metrics_result(metrics, true_labels, predicted_labels):
    metrics_result = []
    for metric in metrics:
        metric.reset_states()
        metric.update_state(true_labels, predicted_labels)
        metrics_result.append(metric.result().numpy())

    return metrics_result

dataset = GOOGL['close']
dataset.loc[dataset.shape[0]]= 0.0
dataset = dataset.iloc[1:]
GOOGL.iloc[:, 1] = dataset.values
dataset = data[:-1]

dataset_to_numpy = dataset.values
dataset.head()

#split the dataset
train_dataset, cross_validation_dataset, test_dataset = split_dataset(dataset_to_numpy)

print("Dataset shape: {:s}".format(str(dataset_to_numpy.shape)))
print("Train dataset shape: {:s}".format(str(train_dataset.shape)))
print("Cross validation dataset shape: {:s}".format(str(cross_validation_dataset.shape)))
print("test dataset shape: {:s}".format(str(test_dataset.shape)))

#plot the data
plt.figure(figsize=(18, 10))
plot_series(np.arange(train_dataset.shape[0]), train_dataset[:, -1], "train dataset")
plot_series(np.arange(train_dataset.shape[0], (cross_validation_dataset.shape[0] + train_dataset.shape[0])), cross_validation_dataset[:, -1], "cross validation dataset")
plot_series(np.arange((cross_validation_dataset.shape[0] + train_dataset.shape[0]), (cross_validation_dataset.shape[0]+ train_dataset.shape[0] + test_dataset.shape[0])), test_dataset[:, -1], "test dataset")
plt.legend(loc='lower left')

#scaling the data
scaler = MinMaxScaler()
scaler = scaler.fit(train_dataset[:, 0:1])

train_dataset_normalized = scaler.transform(train_dataset[:, 0:1])
cross_validation_dataset_normalized = scaler.transform(cross_validation_dataset[:, 0:1])
test_dataset_normalized = scaler.transform(test_dataset[:, 0:1])

WINDOW_SIZE = 15
BATCH_SIZE = 64

windowed_dataset_train, labels_train = create_window_dataset(train_dataset[:, 0:-1], train_dataset[:, -1], WINDOW_SIZE)

windowed_dataset_train, labels_train = create_window_dataset(train_dataset_normalized, train_dataset[:, -1], WINDOW_SIZE)
train_set = tf_dataset(windowed_dataset_train, labels_train, BATCH_SIZE, 1000)
unshuffled_train_set = tf_dataset(windowed_dataset_train, labels_train, BATCH_SIZE, 1000, False)

windowed_dataset_validation, labels_validation = create_window_dataset(cross_validation_dataset_normalized, cross_validation_dataset[:, -1], WINDOW_SIZE)
cross_validation_set = tf_dataset(windowed_dataset_validation, labels_validation, BATCH_SIZE, 1000, False)

windowed_dataset_test, labels_pred = create_window_dataset(test_dataset_normalized, test_dataset[:, -1], WINDOW_SIZE)
test_set = tf_dataset(windowed_dataset_test, labels_pred, 1, 1000, False)

TRAIN_STEP = math.ceil(windowed_dataset_train.shape[0] / BATCH_SIZE)
VALIDATION_STEP = math.ceil(windowed_dataset_validation.shape[0] / BATCH_SIZE)
PRED_STEP = windowed_dataset_test.shape[0]

tf.keras.backend.clear_session()

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv1D(filters=64,
                           kernel_size=5,
                           strides=1,
                           padding="causal",
                           activation="relu",
                           input_shape=windowed_dataset_train.shape[-2:]),
    tf.keras.layers.MaxPooling1D(pool_size=2, strides=1, padding="valid"),
    tf.keras.layers.Conv1D(filters=32, kernel_size=3, strides=1, padding="causal", activation="relu"),
    tf.keras.layers.MaxPooling1D(pool_size=2, strides=1, padding="valid"),
    tf.keras.layers.LSTM(128, return_sequences=True),
    tf.keras.layers.LSTM(128, return_sequences=True),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(1)
])

lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(1e-4,
                                                             decay_steps=100000,
                                                             decay_rate=0.98,
                                                             staircase=False)

model.compile(loss=tf.keras.losses.MeanSquaredError(),
              optimizer=tf.keras.optimizers.SGD(learning_rate=lr_schedule, momentum=0.8),
              metrics=['mae'])
model.summary()

log_dir = "logs\\" + datetime.datetime.now().strftime("%d-%m-%Y_%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

history = model.fit(train_set,
                    epochs=200,
                    steps_per_epoch=TRAIN_STEP,
                    validation_data=cross_validation_set,
                    validation_steps=VALIDATION_STEP,
                    verbose=0,
                    callbacks=[tensorboard_callback])

model.save_weights('weights/inter_model_weights.ckpt')

model.load_weights('weights/inter_model_weights.ckpt')

forecast_train = model.predict(unshuffled_train_set, steps=TRAIN_STEP)
forecast_validation = model.predict(cross_validation_set, steps=VALIDATION_STEP)
forecast_test = model.predict(test_set, steps=PRED_STEP)

total_forecast = np.concatenate((forecast_train[:,0], forecast_validation[:,0], forecast_test[:,0]))
total_labels = np.concatenate((labels_train, labels_validation, labels_pred))

plt.figure(figsize=(10, 8))
plot_series(np.arange(total_labels.shape[0]), total_labels, "real value")
plot_series(np.arange(total_labels.shape[0]), total_forecast, "predicted value")
xpositions = [labels_train.shape[0], (labels_train.shape[0] + labels_validation.shape[0])]
for xp in xpositions:
    plt.axvline(x=xp, linestyle='--')
plt.legend(loc='upper left')

metrics = [
    tf.keras.metrics.MeanAbsoluteError(),
    tf.keras.metrics.MeanAbsolutePercentageError(),
    tf.keras.metrics.MeanSquaredError(),
    tf.keras.metrics.RootMeanSquaredError()
]
train_metrics = get_metrics_result(metrics, labels_train, forecast_train[:,0])
train_metrics.insert(0, 'Train')
val_metrics = get_metrics_result(metrics, labels_validation, forecast_validation[:,0])
val_metrics.insert(0, 'Validation')
test_metrics = get_metrics_result(metrics,labels_pred, forecast_test[:,0])
test_metrics.insert(0, 'test')

COL_NAMES = ['', 'MAE', 'MAPE', 'MSE', 'RMSE']
metrics_table = pd.DataFrame([train_metrics, val_metrics, test_metrics], columns=COL_NAMES)
metrics_table = metrics_table.set_index([''])
metrics_table.round(3)
metrics_table.round(3)

"""# 16 Multivariate LSTM

- A multivariate model is a simplification as well, but it can take several factors into account. For example, a multivariate stock market prediction model can consider the relationship between the closing price and the opening price, moving averages, daily highs, the price of other stocks, and so on.
-Multivariate models thus tend to provide more accurate predictions than univariate models.
"""

import math # Mathematical functions
import numpy as np # Fundamental package for scientific computing with Python
import pandas as pd # Additional functions for analysing and manipulating data
from datetime import date, timedelta, datetime # Date Functions
from pandas.plotting import register_matplotlib_converters # This function adds plotting functions for calender dates
import matplotlib.pyplot as plt # Important package for visualization - we use this to plot the market data
import matplotlib.dates as mdates # Formatting dates
from sklearn.metrics import mean_absolute_error, mean_squared_error # Packages for measuring model performance / errors
from keras.models import Sequential # Deep learning library, used for neural networks
from keras.layers import LSTM, Dense, Dropout # Deep learning classes for recurrent and regular densely-connected layers
from keras.callbacks import EarlyStopping # EarlyStopping during model training
from sklearn.preprocessing import RobustScaler, MinMaxScaler # This Scaler removes the median and scales the data according to the quantile range to normalize the price data
import seaborn as sns

train_df = GOOGL.sort_values(by=['date']).copy()

# We safe a copy of the dates index, before we need to reset it to numbers
date_index = train_df.index

# List of considered Features
FEATURES = ['high', 'low', 'open', 'close', 'volume'
            #, 'Month', 'Year', 'Adj Close'
           ]
([f for f in FEATURES])

# Create the dataset with features and filter the data to the list of FEATURES
data = pd.DataFrame(train_df)
data_filtered = data[FEATURES]

# We add a prediction column and set dummy values to prepare the data for scaling
data_filtered_ext = data_filtered.copy()
data_filtered_ext['Prediction'] = data_filtered_ext['close']
data_filtered_ext.tail()

#Scaling the data

nrows = data_filtered.shape[0]

# Convert the data to numpy values
np_data_unscaled = np.array(data_filtered)
np_data = np.reshape(np_data_unscaled, (nrows, -1))
print(np_data.shape)

# Transform the data by scaling each feature to a range between 0 and 1
scaler = MinMaxScaler()
np_data_scaled = scaler.fit_transform(np_data_unscaled)

# Creating a separate scaler that works on a single column for scaling predictions
scaler_pred = MinMaxScaler()
df_Close = pd.DataFrame(data_filtered_ext['close'])
np_Close_scaled = scaler_pred.fit_transform(df_Close)

"""-In multivarrient models are trained on a three-dimensional data structure.
1. The first dimension is the sequences,
2. the second dimension is the time steps (mini-batches), and
3. the third dimension is the features.
"""

##4 Transforming the Data
sequence_length = 50

# Prediction Index
index_Close = data.columns.get_loc("close")

# Split the training data into train and train data sets
# As a first step, we get the number of rows to train the model on 80% of the data
train_data_len = math.ceil(np_data_scaled.shape[0] * 0.8)

# Create the training and test data
train_data = np_data_scaled[0:train_data_len, :]
test_data = np_data_scaled[train_data_len - sequence_length:, :]

# The RNN needs data with the format of [samples, time steps, features]
# Here, we create N samples, sequence_length time steps per sample, and 6 features
def partition_dataset(sequence_length, data):
    x, y = [], []
    data_len = data.shape[0]
    for i in range(sequence_length, data_len):
        x.append(data[i-sequence_length:i,:]) #contains sequence_length values 0-sequence_length * columsn
        y.append(data[i, index_Close]) #contains the prediction values for validation,  for single-step prediction

    # Convert the x and y to numpy arrays
    x = np.array(x)
    y = np.array(y)
    return x, y

# Generate training data and test data
x_train, y_train = partition_dataset(sequence_length, train_data)
x_test, y_test = partition_dataset(sequence_length, test_data)

# Print the shapes: the result is: (rows, training_sequence, features) (prediction value, )
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

# Validate that the prediction value and the input match up
# The last close price of the second input sample should equal the first prediction value
# The last close price of the second input sample should equal the first prediction value
print(x_train[1][sequence_length-1][index_Close])
print(y_train[0])

"""**Train the Multivariate Prediction Model**
-LSTM layer, which takes our mini-batches as input and returns the whole sequence

-LSTM layer that takes the sequence from the previous layer, but only return 5 values

-Dense layer with 5 neurons

-final dense layer that outputs the predicted value
"""

# Configure the neural network model
model = Sequential()

# Model with n_neurons = inputshape Timestamps, each with x_train.shape[2] variables
n_neurons = x_train.shape[1] * x_train.shape[2]
print(n_neurons, x_train.shape[1], x_train.shape[2])
model.add(LSTM(n_neurons, return_sequences=True, input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(LSTM(n_neurons, return_sequences=False))
model.add(Dense(5))
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Training the model
epochs = 50
batch_size = 16
early_stop = EarlyStopping(monitor='loss', patience=5, verbose=1)
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    validation_data=(x_test, y_test)
                   )

                    #callbacks=[early_stop])

# Plot training & validation loss values
fig, ax = plt.subplots(figsize=(20, 15), sharex=True)
plt.plot(history.history["loss"])
plt.title("Model loss")
plt.ylabel("Loss")
plt.xlabel("Epoch")
ax.xaxis.set_major_locator(plt.MaxNLocator(epochs))
plt.legend(["Train", "Test"], loc="upper left")
plt.grid()
plt.show()

"""The loss drop throghout the training model by imprving the performance."""

# Get the predicted values
y_pred_scaled = model.predict(x_test)

# Unscale the predicted values
y_pred = scaler_pred.inverse_transform(y_pred_scaled)
y_test_unscaled = scaler_pred.inverse_transform(y_test.reshape(-1, 1))

# Mean Absolute Error (MAE)
MAE = mean_absolute_error(y_test_unscaled, y_pred)
print(f'Median Absolute Error (MAE): {np.round(MAE, 2)}')

# Mean Absolute Percentage Error (MAPE)
MAPE = np.mean((np.abs(np.subtract(y_test_unscaled, y_pred)/ y_test_unscaled))) * 100
print(f'Mean Absolute Percentage Error (MAPE): {np.round(MAPE, 2)} %')

# Median Absolute Percentage Error (MDAPE)
MDAPE = np.median((np.abs(np.subtract(y_test_unscaled, y_pred)/ y_test_unscaled)) ) * 100
print(f'Median Absolute Percentage Error (MDAPE): {np.round(MDAPE, 2)} %')

"""### Predicting multivariate stock price for GOOGLE OPENING PRICE"""

# Commented out IPython magic to ensure Python compatibility.
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import datetime

data_1 = pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/individual_stocks_5yr/individual_stocks_5yr/GOOGL_data.csv')

data_1.info()

del data_1["Name"]

import math
data_1["average"] = (data_1["high"] + data_1["low"])/2
data_1.head(2)

input_feature= data_1.iloc[:,[2,6]].values
input_data = input_feature

from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler(feature_range=(0,1))
input_data[:,0:2] = sc.fit_transform(input_feature[:,:])

lookback= 50

test_size=int(.3 * len(data_1))
X=[]
y=[]
for i in range(len(data_1)-lookback-1):
    t=[]
    for j in range(0,lookback):

        t.append(input_data[[(i+j)], :])
    X.append(t)
    y.append(input_data[i+ lookback,1])

X, y= np.array(X), np.array(y)
X_test = X[:test_size+lookback]
X = X.reshape(X.shape[0],lookback, 2)
X_test = X_test.reshape(X_test.shape[0],lookback, 2)
print(X.shape)
print(X_test.shape)

from keras import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(units=30, return_sequences= True, input_shape=(X.shape[1],2)))
model.add(LSTM(units=30, return_sequences=True))
model.add(LSTM(units=30))
model.add(Dense(units=1))
model.summary()

model.compile(optimizer='adam', loss='mean_squared_error')

model.fit(X, y, epochs=100, batch_size=32)

predicted_value= model.predict(X_test)

plt.plot(predicted_value, color= 'red')
plt.plot(input_data[lookback:test_size+(2*lookback),1], color='green')
plt.title("Opening price of stocks sold")
plt.xlabel("Time (latest-> oldest)")
plt.ylabel("Stock Opening Price")
plt.show()

"""#17 Using Prophet

Prophet is a procedure for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects.Prophet’s advantage is that it requires less hyperparameter tuning as it is specifically designed to detect patterns in business time series.
"""

!pip install prophet

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from prophet import Prophet

import warnings
warnings.filterwarnings('ignore')  # Hide warnings
import datetime as dt
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as web
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

!pip install pystan==2.19.1.1
!pip install prophet

!pip install chart-studio

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fbprophet import Prophet
import datetime as dt
from plotly import tools
import chart_studio.plotly as py
import plotly.figure_factory as ff
import plotly.tools as tls
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
import warnings
warnings.filterwarnings("ignore")
# plt.style.available
plt.style.use("seaborn-whitegrid")

GOO = pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/individual_stocks_5yr/individual_stocks_5yr/GOOGL_data.csv',sep=',')

GOO = GOO.rename(columns={'Name': 'Ticks'})
google = GOO.loc[GOO['Ticks'] == 'GOOGL']

google.head()

# Create a copy to avoid the SettingWarning .loc issue
google_df = google.copy()
# Change to datetime datatype
google_df.loc[:, 'date'] = pd.to_datetime(google.loc[:,'date'], format="%Y/%m/%d")

# Drop the columns
ph_df = google_df.drop(['open', 'high', 'low','volume', 'Ticks'], axis=1)
ph_df.rename(columns={'close': 'y', 'date': 'ds'}, inplace=True)
ph_df.head()

plt.figure(figsize=(10,6))
plt.plot(ph_df.set_index('ds'))
plt.legend(['Close'])

m1 = Prophet(daily_seasonality=True)
m1.fit(ph_df)

# Create Future Dates
future_prices = m1.make_future_dataframe(periods=365)
# Predict Prices
forecast1 = m1.predict(future_prices)
forecast1[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

import matplotlib.dates as mdates
# Dates
starting_date = dt.datetime(2020, 10, 29)
starting_date1 = mdates.date2num(starting_date)
pointing_arrow = dt.datetime(2020, 10, 29)
pointing_arrow1 = mdates.date2num(pointing_arrow)
# Learn more Prophet tomorrow and plot the forecast for amazon.
fig = m1.plot(forecast1)
ax1 = fig.add_subplot(111)
ax1.set_title("Google Stock Price Forecast", fontsize=16)
ax1.set_xlabel("date", fontsize=12)
ax1.set_ylabel("Close Price", fontsize=12)
# Forecast initialization arrow
ax1.annotate('Forecast \n Initialization', xy=(pointing_arrow1, 1595), xytext=(starting_date1,1700),
            arrowprops=dict(facecolor='#ff7f50', shrink=0.01),
            )
ax1.axhline(y=1560, color='b', linestyle='-')
plt.show()

"""Black dots : Original Data
The Blue line : the forecast model
The Light Blue area : the confidence interval

-The model used all data for the training (black dots) and predicted the future stock price from mid 2018 to 2019
-It seems that the Google Stock Prices will be around 1400, based on the model prediction.
"""

m1.plot_components(forecast1);

"""Based on the estimated trends, we can see that usually the stock price is maximum in the middle of june and mostly on wednesday. The trend plot shows an increase of the stock price in the near future."""

#Adding the Holiday Effect

ascensionday = pd.DataFrame({
  'holiday': 'AscensionDay',
  'ds': pd.to_datetime(['2015-05-14','2016-05-05','2017-05-25','2018-05-10','2019-05-30']),
  'lower_window': 0,
  'upper_window': 1,
})
christmas = pd.DataFrame({
  'holiday': 'Christmas',
  'ds': pd.to_datetime(['2015-12-25','2016-12-25','2017-12-25','2018-12-25','2019-12-25']),
  'lower_window': -1,
  'upper_window': 7,
})
new_holidays = pd.concat((ascensionday, christmas))
new_holidays.head()

m2 = Prophet(holidays=new_holidays,daily_seasonality=True).fit(ph_df)
future2 = m2.make_future_dataframe(periods=365)
forecast2 = m2.predict(future2)
m2.plot(forecast2);

from fbprophet.plot import add_changepoints_to_plot
fig = m2.plot(forecast2)
a = add_changepoints_to_plot(fig.gca(), m2, forecast2)

from fbprophet.diagnostics import cross_validation
from fbprophet.diagnostics import performance_metrics
from fbprophet.plot import plot_cross_validation_metric
ph_df_cv = cross_validation(m2, initial='380 days', period='90 days', horizon = '60 days')
ph_df_cv.head()

"""- The time series have abrupt changes in the trajectory.
- The red lines, the vertical dashed lines are changepoints Prophet identified where the trend changed, the solid red line is the trend with all seasonality removed.
"""



"""# 18 Stock  Market with three stock market

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
plt.style.use("fivethirtyeight")
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os

all_data=pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/all_stocks_5yr.csv')

all_data = all_data.set_index(pd.DatetimeIndex(all_data["date"].values))
all_data

all_data1 = all_data.copy()
all_data1["Numbers"] = list(range(0, len(all_data1)))
X = np.array(all_data1[["Numbers"]])
y = all_data1["close"].values
lin_model = LinearRegression().fit(X,y)
print("Intercept: ", lin_model.intercept_)
print("Slope: ", lin_model.coef_)

y_pred = lin_model.coef_ * X + lin_model.intercept_
all_data1["Pred"] = y_pred
all_data1["Pred"].plot()
all_data1["close"].plot()
plt.title("Close Price History")

r2_score(all_data1["close"], all_data1["Pred"])

lin_model.coef_*len(all_data1)+1+ lin_model.intercept_

"""#19 Comapring and evaluating between models"""

GL3= GL.copy()

GL3

GL3.close

## For data
## For Lstm
from tensorflow.keras import models, layers, preprocessing as kprocessing
## For Prophet
from fbprophet import Prophet

GL3= pd.read_csv('/content/gdrive/MyDrive/seclea/demo_applications/Stock_data/individual_stocks_5yr/individual_stocks_5yr/GOOGL_data.csv',sep=',', index_col='date', parse_dates=['date'], date_parser=dateparse).fillna(0)

GL3.head()

ts= GL3.close

ts.head()

'''
Split train/test from any given data point.
:parameter
    :param ts: pandas Series
    :param test: num or str - test size (ex. 0.20) or index position
                 (ex. "yyyy-mm-dd", 1000)
:return
    ts_train, ts_test
'''
def split_train_test(ts, test=0.20, plot=True, figsize=(15,5)):
    ## define splitting point
    if type(test) is float:
        split = int(len(ts)*(1-test))
        perc = test
    elif type(test) is str:
        split = ts.reset_index()[
                      ts.reset_index().iloc[:,0]==test].index[0]
        perc = round(len(ts[split:])/len(ts), 2)
    else:
        split = test
        perc = round(len(ts[split:])/len(ts), 2)
    print("--- splitting at index: ", split, "|",
          ts.index[split], "| test size:", perc, " ---")

    ## split ts
    ts_train = ts.head(split)
    ts_test = ts.tail(len(ts)-split)
    if plot is True:
        fig, ax = plt.subplots(nrows=1, ncols=2, sharex=False,
                               sharey=True, figsize=figsize)
        ts_train.plot(ax=ax[0], grid=True, title="Train",
                      color="black")
        ts_test.plot(ax=ax[1], grid=True, title="Test",
                     color="black")
        ax[0].set(xlabel=None)
        ax[1].set(xlabel=None)
        plt.show()

    return ts_train, ts_test

ts_train, ts_test = split_train_test(ts, test="2015-06-01")

'''
Evaluation metrics for predictions.
:parameter
    :param dtf: DataFrame with columns raw values, fitted training
                 values, predicted test values
:return
    dataframe with raw ts and forecast
'''
def utils_evaluate_forecast(GL3, title, plot=True, figsize=(20,13)):
    try:
        ## residuals
        GL3["residuals"] = GL3["ts"] - GL3["model"]
        GL3["error"] = GL3["ts"] - GL3["forecast"]
        GL3["error_pct"] = GL3["error"] / GL3["ts"]

        ## kpi
        residuals_mean = GL3["residuals"].mean()
        residuals_std = GL3["residuals"].std()
        error_mean = GL3["error"].mean()
        error_std = Gl3["error"].std()
        mae = GL3["error"].apply(lambda x: np.abs(x)).mean()
        mape = GL3["error_pct"].apply(lambda x: np.abs(x)).mean()
        mse = GL3["error"].apply(lambda x: x**2).mean()
        rmse = np.sqrt(mse)  #root mean squared error

        ## intervals
        GL3["conf_int_low"] = GL3["forecast"] - 1.96*residuals_std
        GL3["conf_int_up"] = GL3["forecast"] + 1.96*residuals_std
        Gl3["pred_int_low"] = Gl3["forecast"] - 1.96*error_std
        Gl3["pred_int_up"] = Gl3["forecast"] + 1.96*error_std

        ## plot
        if plot==True:
            fig = plt.figure(figsize=figsize)
            fig.suptitle(title, fontsize=20)
            ax1 = fig.add_subplot(2,2, 1)
            ax2 = fig.add_subplot(2,2, 2, sharey=ax1)
            ax3 = fig.add_subplot(2,2, 3)
            ax4 = fig.add_subplot(2,2, 4)
            ### training
            Gl3[pd.notnull(Gl3["model"])][["ts","model"]].plot(color=["black","green"], title="Model", grid=True, ax=ax1)
            ax1.set(xlabel=None)
            ### test
            Gl3[pd.isnull(GL3["model"])][["ts","forecast"]].plot(color=["black","red"], title="Forecast", grid=True, ax=ax2)
            ax2.fill_between(x=GL3.index, y1=GL3['pred_int_low'], y2=GL3['pred_int_up'], color='b', alpha=0.2)
            ax2.fill_between(x=GL3.index, y1=GL3['conf_int_low'], y2=GL3['conf_int_up'], color='b', alpha=0.3)
            ax2.set(xlabel=None)
            ### residuals
            GL3[["residuals","error"]].plot(ax=ax3, color=["green","red"], title="Residuals", grid=True)
            ax3.set(xlabel=None)
            ### residuals distribution
            GL3[["residuals","error"]].plot(ax=ax4, color=["green","red"], kind='kde', title="Residuals Distribution", grid=True)
            ax4.set(ylabel=None)
            plt.show()
            print("Training --> Residuals mean:", np.round(residuals_mean), " | std:", np.round(residuals_std))
            print("Test --> Error mean:", np.round(error_mean), " | std:", np.round(error_std),
                  " | mae:",np.round(mae), " | mape:",np.round(mape*100), "%  | mse:",np.round(mse), " | rmse:",np.round(rmse))

        return GL3[["ts","model","residuals","conf_int_low","conf_int_up",
                    "forecast","error","pred_int_low","pred_int_up"]]

    except Exception as e:
        print("--- got error ---")
        print(e)

## Keras models
model = models.Sequential()
model.add( layers.LSTM(input_shape=(1,365), units=50,
           activation='relu', return_sequences=False) )
model.add( layers.Dense(1) )
model.compile(optimizer='adam', loss='mean_absolute_error')

'''
Preprocess a ts partitioning into X and y.
:parameter
    :param ts: pandas timeseries
    :param s: num - number of observations per seasonal (ex. 7 for weekly seasonality with daily data, 12 for yearly seasonality with monthly data)
    :param scaler: sklearn scaler object - if None is fitted
    :param exog: pandas dataframe or numpy array
:return
    X, y, scaler
'''
def utils_preprocess_ts(ts, s, scaler=None, exog=None):
    ## scale
    if scaler is None:
        scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
    ts_preprocessed = scaler.fit_transform(ts.values.reshape(-1,1)).reshape(-1)

    ## create X,y for train
    ts_preprocessed = kprocessing.sequence.TimeseriesGenerator(data=ts_preprocessed,
                                                               targets=ts_preprocessed,
                                                               length=s, batch_size=1)
    lst_X, lst_y = [], []
    for i in range(len(ts_preprocessed)):
        xi, yi = ts_preprocessed[i]
        lst_X.append(xi)
        lst_y.append(yi)
    X = np.array(lst_X)
    y = np.array(lst_y)
    return X, y, scaler
'''
Get fitted values.
'''
def utils_fitted_lstm(ts, model, scaler, exog=None):
    ## scale
    ts_preprocessed = scaler.fit_transform(ts.values.reshape(-1,1)).reshape(-1)

    ## create Xy, predict = fitted
    s = model.input_shape[-1]
    lst_fitted = [np.nan]*s
    for i in range(len(ts_preprocessed)):
        end_ix = i + s
        if end_ix > len(ts_preprocessed)-1:
            break
        X = ts_preprocessed[i:end_ix]
        X = np.array(X)
        X = np.reshape(X, (1,1,X.shape[0]))
        fit = model.predict(X)
        fit = scaler.inverse_transform(fit)[0][0]
        lst_fitted.append(fit)
    return np.array(lst_fitted)
'''
Predict ts using previous predictions.
'''
def utils_predict_lstm(ts, model, scaler, pred_ahead, exog=None):
    ## scale
    s = model.input_shape[-1]
    ts_preprocessed = list(scaler.fit_transform(ts[-s:].values.reshape(-1,1)))

    ## predict, append, re-predict
    lst_preds = []
    for i in range(pred_ahead):
        X = np.array(ts_preprocessed[len(ts_preprocessed)-s:])
        X = np.reshape(X, (1,1,X.shape[0]))
        pred = model.predict(X)
        ts_preprocessed.append(pred)
        pred = scaler.inverse_transform(pred)[0][0]
        lst_preds.append(pred)
    return np.array(lst_preds)

def fit_lstm(ts_train, ts_test, model, exog=None, s=20,
             figsize=(15,5)):
  print("Seasonality: using the last", s, "observations to predict the next 1")

    ## preprocess train
X_train, y_train, scaler = ts_preprocessed(ts_train, scaler=None, exog=None, s=20)

    ## lstm

if model is None:
        model = models.Sequential()
        model.add( layers.LSTM(input_shape=X_train.shape[1:], units=50, activation='relu', return_sequences=False) )
        model.add( layers.Dense(1) )
        model.compile(optimizer='adam', loss='mean_absolute_error')

    ## train
print(model.summary())
training = model.fit(x=X_train, y=y_train, batch_size=1,
                         epochs=100, shuffle=True, verbose=0,
                         validation_split=0.3)

GL3_train = ts_train.to_frame(name="ts")
GL3_train["model"] = utils_fitted_lstm(ts_train, training.model,
                                           scaler, exog)
GL3_train["model"] = GL3_train["model"].fillna(method='bfill')

    ## test
preds = utils_predict_lstm(ts_train[-s:], training.model,
                               scaler, pred_ahead=len(ts_test),
                               exog=None)
GL3_test = ts_test.to_frame(name="ts").merge(
                       pd.DataFrame(data=preds, index=ts_test.index,
                                    columns=["forecast"]),
               how='left', left_index=True, right_index=True)

    ## evaluate
GL3 = GL3_train.append(GL3_test)
GL3 = utils_evaluate_forecast(GL3, figsize=figsize,
                                  title="LSTM (memory:"+str(s)+")")
return GL3, training.model